lang = "TS"
package_type = "library"

[[links]]
icon = "FaNpm"
internal = true
label = "View on NPM"
link = "https://www.npmjs.com/package/@ginger-society/ginger-book"

[[links]]
icon = "FaCodeBranch"
internal = true
label = "Pull Requests"
link = "https://github.com/ginger-society/ginger-book/pulls"

[[links]]
icon = "FaRegPlayCircle"
internal = true
label = "Pipelines"
link = "https://github.com/ginger-society/ginger-book/actions"

[[links]]
icon = "FaGithub"
internal = true
label = "Browse Repo"
link = "https://github.com/ginger-society/ginger-book"
