[version]
channel = "Final"
major = 4
minor = 2
patch = 0
revision = 0

[[references]]
file_name = "packages/ginger-book/package.json"
output_type = "String"
variable = "version"

[settings]
git_url_prefix = "https://github.com/ginger-society/ginger-ui"
