name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ginger-apps
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ginger-society/infra-as-code-repo/main/rust-helpers/install-pipeline-clis.sh)"

      - name: Authenticate with ginger-auth
        id: ginger-auth
        run: ginger-auth token-login ${{ secrets.GINGER_TOKEN }}

      - name: Update pipeline to running
        run: ginger-connector update-pipeline stage running

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.7.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.5
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build tech docs
        run: pnpm jsd

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=admin@gingersociety.org
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      

      - name: Build prod release
        run: pnpm build
        
      - name: Create Release Pull Request or Publish to npm
        run: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing next version
        run: cd packages/ginger-book && pnpm types && ./publish-next.js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Step to configure AWS credentials for accessing S3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change the region as needed

      # Step to upload documentation to the S3 bucket
      - name: Upload docs to S3
        run: aws s3 cp ./docs s3://ginger-book-tech-docs/ --recursive
        # Replace ./path-to-docs with the actual path to the documentation files you want to upload

      - name: Update pipeline to running
        run: ginger-connector update-pipeline stage passing
