name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.7.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.5
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install playwright
        run: pnpm exec playwright install --with-deps

      - name: Eslint
        run: pnpm lint

      - name: Typescript
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Unit and e2e tests
        run: pnpm test